{% set name = "xdatasets" %}
{% set version = "0.3.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xdatasets-{{ version }}.tar.gz
  sha256: 2efed0cfc39046827014b5ce89bbccd0edd2c86dcfa171d77a01b08b7e53b45f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck >=1.3.1
    - cf_xarray >=0.6.1
    - cftime >=1.4.1
    - clisops >=0.9.2
    - dask-core >=2.6
    - dask-geopandas >=0.4.1
    - geopandas >=1.0
    - intake
    - intake-geopandas
    - intake-xarray >=0.6.1,<2.0.0
    - ipython >=8.5.0
    - jsonpickle
    - numpy >=1.23
    - pandas >=1.5
    - s3fs
    - setuptools
    - scipy >=1.9.0
    - tqdm
    - xarray >=2023.1
    - wheel
    - zarr >=2.11.1

test:
  imports:
    - xdatasets
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/hydrologie/xdatasets
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy access to Earth observation datasets with xarray.
  dev_url: https://github.com/hydrologie/xdatasets
  doc_url: https://xdatasets.readthedocs.io

extra:
  recipe-maintainers:
    - RondeauG
    - Zeitsperre
    - sebastienlanglois
